### ISSUE TITLE
Image Repository Example

### ISSUE THREAD

**Issue by fulviocanducci** [ripplr-io/docr-image-remove#2]
The `image-repository` configuration was not very clear, for example you have to put in the full name example: `registry.digitalocean.com/ex/ab:v1` or `ex/ab:v1`, could you please exemplify?

Other Example:

```php
- name: Remove old images from Container Registry
      uses: ripplr-io/docr-image-remove@v1
      with:
        image_repository: ex/ab:v1
        buffer_size: 10
```

**or** 

```
- name: Remove old images from Container Registry
      uses: ripplr-io/docr-image-remove@v1
      with:
        image_repository: registry.digitalocean.com/ex/ab:v1
        buffer_size: 10
```

Could you clarify me about this configuration what should I pass as a value?

**Comment by JeffreySoriano5** [comment]
Did you find what was the correct way?

**Comment by fulviocanducci** [comment]
> ripplr-io/docr-image-remove

Yes!

The configuration requires the short name to work, example:

```
- name: Remove Old Images From Container Registry
  uses: ripplr-io/docr-image-remove@v1
  with:
	image_repository: "Short_Name"
	buffer_size: 1   
```

You just need to be logged in to Digital Ocean via doctl:

```
- name: Install doctl
  uses: digitalocean/action-doctl@v2
  with:
	token: ${{ secrets.DIGITALOCEAN_ACCESS }}

- name: Log in to DigitalOcean Container Registry with Short-lived Credentials
  run: doctl registry login
```

this was performed by github actions
